[package]
name = "pss-minimal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
pem = "2.0.1"
rand = "0.8.5"
ring = "0.16.20"
rsa = "0.8.2"
sha2 = "0.10.6"
simple_asn1 = "0.6.2"
